<%@ Page Language="VB" MasterPageFile="~/Admin/adminmst.master" AutoEventWireup="false" CodeFile="order.aspx.vb" Inherits="Admin_order" title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
.heading
        {
            text-align: center;
            font-size: x-large;
            background-color: #8bc34a;
            height:50px;
        }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="style1">
        <tr>
            <td class="heading" colspan="4">
                <strong>Orders Details</strong></td>
        </tr>
        
        <tr>
            <td colspan="2" style="text-align: center">
                <asp:Label ID="lblmsg" runat="server" style="text-align: left" ForeColor="Red"></asp:Label>
            </td>
            <td colspan="2">
                &nbsp;</td>
        </tr>
        <tr>
            <td width="8%">
                &nbsp;</td>
            <td colspan="2">
                <asp:GridView ID="grvorder" runat="server" AllowPaging="True" 
                    AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" CellPadding="10" DataKeyNames="orderid" 
                    style="text-align: center" Width="100%" ForeColor="Black" 
                    GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:TemplateField HeaderText="Order ID">
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("orderid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="User ID">
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("userid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Product ID">
                            <ItemTemplate>
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("pid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Product">
                            <ItemTemplate>
                                <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("imageurl") %>' />
                            </ItemTemplate>
                            <ControlStyle CssClass="pimg" Height="70px" Width="100px" />
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Product Name">
                            <ItemTemplate>
                                <asp:Label ID="Label8" runat="server" Text='<%# Bind("Pname") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Price">
                            <ItemTemplate>
                                <asp:Label ID="Label7" runat="server" Text='<%# Bind("price") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Quantity">
                            <ItemTemplate>
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("qty") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Payment ID">
                            <ItemTemplate>
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("paymentid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="orderstatus" HeaderText="Order Status" />
                        <asp:TemplateField HeaderText="Order Date">
                            <ItemTemplate>
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("orderdate") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#8bc34a" ForeColor="White" Font-Bold="True" />
                    <HeaderStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="Black" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="Black" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                   <%-- <SortedAscendingCellStyle BackColor="#FDF5AC" />
                    <SortedAscendingHeaderStyle BackColor="#4D0000" />
                    <SortedDescendingCellStyle BackColor="#FCF6C0" />
                    <SortedDescendingHeaderStyle BackColor="#820000" />--%>
                </asp:GridView>
                <asp:Label ID="lblcount" runat="server" Text=""></asp:Label>     
            </td>
            <td width="8%">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="4">
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>

