<%@ Page Language="VB" MasterPageFile="~/Admin/adminmst.master" AutoEventWireup="false" CodeFile="payment.aspx.vb" Inherits="Admin_payment" title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
 <style type="text/css">
        .heading
        {
            text-align: center;
            font-size: x-large;
            background-color: #8bc34a;
            height:50px;
        }
     .style7
     {
         width: 622px;
     }
    
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
 <table class="style1">
        <tr>
             <td class="heading" colspan="3">
                <strong>Payments Datails</strong></td>
                
        </tr>
        
        <tr>
        
         <td  align="center" class="style7">
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Calendar ID="Calendar1" 
                    runat="server" BackColor="White" 
                    BorderColor="#3366CC" BorderWidth="1px" CellPadding="1" 
                    DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" 
                    ForeColor="#003399" Height="200px" Width="385px">
                    <SelectedDayStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                    <SelectorStyle BackColor="#99CCCC" ForeColor="#336666" />
                    <WeekendDayStyle BackColor="#CCCCFF" />
                    <TodayDayStyle BackColor="#99CCCC" ForeColor="White" />
                    <OtherMonthDayStyle ForeColor="#999999" />
                    <NextPrevStyle Font-Size="8pt" ForeColor="#CCCCFF" />
                    <DayHeaderStyle BackColor="#99CCCC" ForeColor="#336666" Height="1px" />
                    <TitleStyle BackColor="#003399" BorderColor="#3366CC" BorderWidth="1px" 
                        Font-Bold="True" Font-Size="10pt" ForeColor="#CCCCFF" Height="25px" />
                </asp:Calendar>
            
                            
                            <br />
            
                            
                            </td>
                            
            
            <td  align="left" >
                <asp:RadioButtonList ID="radiobuttonlist" runat="server" 
                    RepeatDirection="Vertical" Width="100%" AutoPostBack="True" Height="188px">
                    <asp:ListItem Value="Credit/Debit Card">Credit/Debit Card</asp:ListItem>
                    <asp:ListItem Value="Google Pay">Google Pay</asp:ListItem>
                    <asp:ListItem Value="UPI">UPI</asp:ListItem>
                    <asp:ListItem Value="Cash On Delivery">Cash On Delivery</asp:ListItem>
                </asp:RadioButtonList>
            </td>
           
            
        </tr>
       
        
        <tr>
         
             
            <td colspan="2" align="center">
                <asp:GridView ID="grvpayment" runat="server" AllowPaging="True" 
                    AutoGenerateColumns="False" CellPadding="10" DataKeyNames="paymentid" 
                    Width="94%" style="text-align: center" ForeColor="#333333" 
                    GridLines="None" Font-Size="Large" AutoGenerateDeleteButton="True">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField DataField="paymentid" HeaderText="Payment ID" />
                        <asp:BoundField DataField="pid" HeaderText="Product ID" />
                        <asp:BoundField DataField="userid" HeaderText="User ID" />
                        <asp:BoundField DataField="paymenttype" HeaderText="Payment Type" />
                        <asp:BoundField DataField="total" HeaderText="Total" />
                        <asp:BoundField DataField="paystatus" HeaderText="Payment Status" />
                        <asp:BoundField DataField="date" HeaderText="DateTime" />
                    </Columns>
                    <FooterStyle BackColor="#8bc34a" ForeColor="White" Font-Bold="True" />
                    <HeaderStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                    <PagerStyle ForeColor="#333333" HorizontalAlign="Center" BackColor="#FFCC66" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                   <%-- <SortedAscendingCellStyle BackColor="#FDF5AC" />
                    <SortedAscendingHeaderStyle BackColor="#4D0000" />
                    <SortedDescendingCellStyle BackColor="#FCF6C0" />
                    <SortedDescendingHeaderStyle BackColor="#820000" />--%>
                    
                </asp:GridView>
               
            </td>
            
        </tr>
        <tr>
        <td align="left" class="style7"> 
        <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
            <asp:Label  ID="lblcount" runat="server" Text=""></asp:Label>
                <br />
                <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Label ID="lblTotalSum" runat="server" Text=""></asp:Label></td>
            
            </tr>
    </table>
</asp:Content>

