<%@ Page Language="VB" MasterPageFile="~/Admin/adminmst.master" AutoEventWireup="false" CodeFile="reports.aspx.vb" Inherits="Admin_reports" title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

<style type="text/css">
.heading
        {
            text-align: center;
            font-size: x-large;
            background-color: #8bc34a;
            height:50px;
        }
         .bg-color
    {
         background-color:#1d232f;
        color:White;    
    }
     .style10
        {
            width: 106px;
        }
        .style11
        {
        width: 490px;
        text-align: left;
    }
    .style12
    {
        text-align: left;
        margin-left: 160px;
    }
    .bg-color
    {
         background-color:#1d232f;
        color:White;    
    }
    .btn-payment
    {
         font-size:15px;
         letter-spacing: 1px;
         font-weight  : 600;
         border-radius: 5px;
         background-color:#8bc34a;
         cursor:pointer;
    }
    .btn-payment:hover
    {
        background-color:8bc34a;
        color: White;
       }
    .style13
    {
        width: 106px;
        height: 29px;
    }
    .style14
    {
        width: 490px;
        text-align: left;
        height: 29px;
    }
    .style15
    {
        height: 29px;
    }
    .style16
    {
        background-color: #1d232f;
        color: White;
        height: 5px;
    }
    .style1 tblpayment
    {
    	}
    .style1 bgcolor-payment
    {
    	}
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

 <table class="style1">
        <tr>
            <td class="heading" colspan="4">
                <strong>Reports</strong></td>
        </tr>
       
       
    </table>
    
    
    <table class="style1 tblpayment"  >
        <tr>
            <td colspan="3">
                <h1 style="text-align: center ">
                    </h1>
            </td>
        </tr>
       
        <tr>
        
            
            <td colspan="2" class="bg-color-procat" width="25%" align="center"><asp:Calendar ID="Calendar1" 
                    runat="server" BackColor="White" 
                    BorderColor="#3366CC" BorderWidth="1px" CellPadding="1" 
                    DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" 
                    ForeColor="#003399" Height="200px" Width="420px">
                    <SelectedDayStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                    <SelectorStyle BackColor="#99CCCC" ForeColor="#336666" />
                    <WeekendDayStyle BackColor="#CCCCFF" />
                    <TodayDayStyle BackColor="#99CCCC" ForeColor="White" />
                    <OtherMonthDayStyle ForeColor="#999999" />
                    <NextPrevStyle Font-Size="8pt" ForeColor="#CCCCFF" />
                    <DayHeaderStyle BackColor="#99CCCC" ForeColor="#336666" Height="1px" />
                    <TitleStyle BackColor="#003399" BorderColor="#3366CC" BorderWidth="1px" 
                        Font-Bold="True" Font-Size="10pt" ForeColor="#CCCCFF" Height="25px" />
                </asp:Calendar>
                            </td>
           
            <td width="25%">&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center">
                <asp:Label ID="lblmsg" runat="server" style="text-align: left" ForeColor="Red"></asp:Label>
            </td>
            <td colspan="2">
                &nbsp;</td>
        </tr>
        <tr>
            <td width="8%">
                &nbsp;</td>
            <td colspan="2">
                <asp:GridView ID="grvorder" runat="server" AllowPaging="True" 
                    AutoGenerateColumns="False" AutoGenerateDeleteButton="False" 
                    AutoGenerateEditButton="False" CellPadding="10" DataKeyNames="orderid" 
                    style="text-align: center; margin-right: 0px;" Width="106%" ForeColor="Black" 
                    GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:TemplateField HeaderText="Order ID">
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("orderid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="User ID">
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("userid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Product ID">
                            <ItemTemplate>
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("pid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Product">
                            <ItemTemplate>
                                <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("imageurl") %>' />
                            </ItemTemplate>
                            <ControlStyle CssClass="pimg" Height="70px" Width="100px" />
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Product Name">
                            <ItemTemplate>
                                <asp:Label ID="Label8" runat="server" Text='<%# Bind("Pname") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Price">
                            <ItemTemplate>
                                <asp:Label ID="Label7" runat="server" Text='<%# Bind("price") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Quantity">
                            <ItemTemplate>
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("qty") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Payment ID">
                            <ItemTemplate>
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("paymentid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="orderstatus" HeaderText="Order Status" />
                        <asp:TemplateField HeaderText="Order Date">
                            <ItemTemplate>
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("orderdate") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#8bc34a" ForeColor="White" Font-Bold="True" />
                    <HeaderStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="Black" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="Black" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                   <%-- <SortedAscendingCellStyle BackColor="#FDF5AC" />
                    <SortedAscendingHeaderStyle BackColor="#4D0000" />
                    <SortedDescendingCellStyle BackColor="#FCF6C0" />
                    <SortedDescendingHeaderStyle BackColor="#820000" />--%>
                </asp:GridView>
                <asp:Label ID="lblcount" runat="server" Text=""></asp:Label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <br />
                <br />
                <asp:Label ID="lblTotalSum" runat="server" Text=""></asp:Label>
    
            </td>
            <td width="8%">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="4">
                &nbsp;</td>
        </tr>
                    
               
        
    </table>
</asp:Content>

