<%@ Page Language="VB" MasterPageFile="~/Admin/adminmst.master" AutoEventWireup="false" CodeFile="user.aspx.vb" Inherits="Admin_user" title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
.heading
        {
            text-align: center;
            font-size: x-large;
            background-color: #8bc34a;
            height:50px;
        }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="style1">
        <tr>
            <td class="heading" colspan="6">
                <strong>Users Details</strong></td>
        </tr>
        <tr>
            <td colspan="2">
                &nbsp;</td>
            <td colspan="2">
                <asp:Label ID="lblmsg" runat="server" ForeColor="Red"></asp:Label>
            </td>
            <td colspan="2">
                &nbsp;</td>
        </tr>
        <tr>
            <td width="8%">
                &nbsp;</td>
            <td colspan="4">
                <asp:GridView ID="grvuser" runat="server" AutoGenerateColumns="False" 
                    CellPadding="4" Width="100%" AllowPaging="True" 
                    AutoGenerateDeleteButton="True" DataKeyNames="userid" 
                    style="text-align: center" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField DataField="userid" HeaderText="User ID" />
                        <asp:BoundField DataField="username" HeaderText="User Email" />
                        <asp:BoundField DataField="password" HeaderText="User Password" />
                        <asp:BoundField DataField="email" HeaderText="User Email" />
                        <asp:BoundField DataField="gender" HeaderText="Gender" />
                        <asp:BoundField DataField="address" HeaderText="Address" />
                        <asp:BoundField DataField="mobileno" HeaderText="Phone No" />
                    </Columns>
                    <FooterStyle BackColor="#8bc34a" ForeColor="White" Font-Bold="True" />
                    <HeaderStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                    <%--<SortedAscendingCellStyle BackColor="#FDF5AC" />
                    <SortedAscendingHeaderStyle BackColor="#4D0000" />
                    <SortedDescendingCellStyle BackColor="#FCF6C0" />
                    <SortedDescendingHeaderStyle BackColor="#820000" />--%>
                </asp:GridView>
            </td>
            <td width="8%">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3">
                &nbsp;</td>
            <td colspan="3">
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>

