
<%@ Page Language="VB" MasterPageFile="~/user/usermast.master" AutoEventWireup="false" CodeFile="cart.aspx.vb" Inherits="cart" title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style8
        {
            height: 70px;
            text-align: center;
        }
        .a-right
        { text-align: right;
        }
        
        .style9
        {
            height: 36px;
        }
        .style10
        {
            text-align: right;
            height: 41px;
        }
        .style11
        {
            height: 41px;
        }
        
    .style12
    {
        width: 11%;
    }
    .style14
    {
        text-align: right;
        height: 41px;
        width: 11%;
    }
        
        .style15
        {
            text-align: center;
        }
        .style17
        {
            text-align: right;
            height: 37px;
        }
        .style18
        {
            height: 37px;
        }
        
    .style19
    {
        color: #FFFFFF;
    }
        
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
   <table class="style1">
        <tr>
            <td class="style8" colspan="3">
                <h1>
                    My Cart</h1>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblmsg" runat="server"></asp:Label>
            </td>
            <td class="style12">
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3">
                <table class="style1">
                    <tr>
                        <td colspan="3" style="text-align:center">
                            <asp:Label ID="lblempty" runat="server" 
                                Text="Your cart Is Empty Please Select A Items" Visible="False"></asp:Label>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td style="text-align:center">
                            <asp:GridView ID="grvcart" runat="server" AutoGenerateColumns="False" 
                                AutoGenerateDeleteButton="True" BackColor="#DEBA84" BorderColor="#DEBA84" 
                                BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" 
                                DataKeyNames="cartid" Width="100%" AutoGenerateEditButton="True">
                                <Columns>
                                    <asp:TemplateField HeaderText="Image">
                                        <ItemTemplate>
                                            <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("imageurl") %>' />
                                        </ItemTemplate>
                                        <ControlStyle Height="70px" Width="100px" CssClass="pimg" />
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Name">
                                        <ItemTemplate>
                                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("pname") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Price">
                                        <ItemTemplate>
                                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("price") %>'></asp:Label>
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                        <asp:Label ID="lblprice" runat="server" Text='<%# Eval("price") %>'></asp:Label>
                                        </EditItemTemplate>
                                    </asp:TemplateField>
                                    <asp:BoundField DataField="qty" HeaderText="Quantity" />
                                    <asp:TemplateField HeaderText="Total">
                                        <ItemTemplate>
                                            <asp:Label ID="lbltotal" runat="server" Text='<%# Bind("total") %>'></asp:Label>
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                        <asp:Label ID="lbltotal" runat="server" Text='<%# Eval("total") %>'></asp:Label>
                                        </EditItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                                <FooterStyle BackColor="#8bc34a" ForeColor="#8C4510" />
                                <HeaderStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                                <PagerStyle ForeColor="#8bc34a" HorizontalAlign="Center" />
                                <RowStyle BackColor="#FFF7E7" ForeColor="Black" />
                                <SelectedRowStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                               <%-- <SortedAscendingCellStyle BackColor="#FFF1D4" />
                                <SortedAscendingHeaderStyle BackColor="#B95C30" />
                                <SortedDescendingCellStyle BackColor="#F1E5CE" />
                                <SortedDescendingHeaderStyle BackColor="#93451F" />--%>
                            </asp:GridView>
                        </td>
                        <td>
                            &nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td class="style9" colspan="3">
                <table class="style1">
                    <tr>
                        <td class="style15" colspan="2" style="text-align:center">
                <asp:Button ID="btneback" runat="server" Text="Add Items" class="btn-sty" 
                    PostBackUrl="~/user/home.aspx" Visible="False" />
                        </td>
                    </tr>
                    <tr>
                        <td class="style18">
                            </td>
                        <td class="style17">
                            &nbsp;<asp:Label ID="lbltext" runat="server" Font-Bold="True" 
                                Text="Grand Total:"></asp:Label>
                            <asp:Label ID="lblgtotal" runat="server"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        </td>
                    </tr>
                </table>
                </td>
        </tr>
        <tr>
            <td class="style10">
                <asp:Button ID="btnback" runat="server" Text="Add More Items" class="btn-sty" 
                    PostBackUrl="~/user/home.aspx" />
            </td>
            <td class="style14">
                <asp:Button ID="btnpay" runat="server" Text="Check Out" class="btn-sty" 
                    PostBackUrl="~/user/summry.aspx" />
            </td>
            <td class="style11">
                </td>
        </tr>
    </table>
</asp:Content>

