<%@ Page Language="VB" MasterPageFile="~/user/usermast.master" AutoEventWireup="false" CodeFile="order.aspx.vb" Inherits="order" title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
    .style8
        {
            height: 70px;
            text-align: center;
            color:black;
        }
          .style15
        {
            text-align: center;
        }
       </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="style1">
        <tr>
            <td class="style8" colspan="4">
                <h1> My Orders </h1>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="">
                &nbsp;</td>
            <td colspan="2">
                <asp:Label ID="lblmsg" runat="server" style="text-align: center" 
                    ForeColor="Red" Visible="False"></asp:Label>
            </td>
        </tr>
        <tr>
               <td colspan="3" style="text-align:center">
            <asp:Label ID="lblempty" runat="server" Text="Empty Please Make Order" Visible="False"></asp:Label>
                </td>
                        </tr>
        <tr>
            <td>
                &nbsp;</td>
            <td colspan="2">
                <asp:GridView ID="grvorder" runat="server" AllowPaging="True" 
                    AutoGenerateColumns="False" CellPadding="3" DataKeyNames="orderid" 
                    style="text-align: center" Width="100%" BackColor="#DEBA84" 
                    BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellSpacing="2" 
                    AutoGenerateDeleteButton="True">
                    <Columns>
                        <asp:ImageField DataImageUrlField="imageurl" HeaderText="Product">
                            <ControlStyle Height="70px" Width="100px" CssClass="pimg" />
                        </asp:ImageField>
                        <asp:TemplateField HeaderText="Order ID">
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("orderid") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="Pname" HeaderText="Product Name" />
                        <asp:BoundField DataField="price" HeaderText="Price" />
                        <asp:BoundField DataField="qty" HeaderText="Quantity" />
                        <asp:BoundField DataField="total" HeaderText="Total" />
                        <asp:BoundField DataField="paymentid" HeaderText="PaymentId" />
                        <asp:BoundField DataField="orderstatus" HeaderText="Order Status" />
                        <asp:TemplateField HeaderText="Order Date">
                            <ItemTemplate>
                                <asp:Label ID="Label6" runat="server" Text='<%# Bind("orderdate") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#8bc34a" ForeColor="#8C4510" />
                                <HeaderStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                                <PagerStyle ForeColor="#8bc34a" HorizontalAlign="Center" />
                                <RowStyle BackColor="#FFF7E7" ForeColor="Black" />
                                <SelectedRowStyle BackColor="#8bc34a" Font-Bold="True" ForeColor="White" />
                    <%--<SortedAscendingCellStyle BackColor="#FFF1D4" />
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />
                    <SortedDescendingHeaderStyle BackColor="#93451F" />--%>
                </asp:GridView>
            </td>
            <td>
                &nbsp;</td>
               
        </tr> <tr>
                        <td class="style15" colspan="2">
                <asp:Button ID="btneback" runat="server" Text="Make Order" class="btn-sty" 
                    PostBackUrl="~/user/cart.aspx" Visible="False" />
                        </td>
                    </tr>
        <tr>
            <td colspan="4">
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>

